##################
#General Settings#
##################

## Whether or not to log to the console when a player receives their payment.
logToConsole: false

## Whether or not to send a message to a player when they receive money for playtime.
messagePlayer: false

## Whether or not to monitor a player's AFK status
checkForAFK: true

## How long, in seconds, before a player will receive payment.
delay: 60

## The amount of in-game currency to give to a player after delay.
nonDonatorAmount: 0.10
donatorAmount: 0.50

## The delay, in seconds, before a player is marked as AFK.
timeout: 15
