name: PlaytimeRewards
main: com.ipwnage.playtimerewards.CashMoney
author: [Drew1895, Protocol_7]
version: 1.1
depend: [Vault]
commands:
  pr:
      description: This is a test command.
      usage: /pr
     
 
permissions:
    ipwnage.staff:
        description: Give this to staff so that they can use the commands in this plugin.
        default: false
    ipwnage.rate.donator:
        description: Allows money generation at a higher rate.
        default: false
